include: all_lint_rules.yaml
analyzer:
  exclude:
    - "lib/*.g.dart"
    - "lib/main.g.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    
    
    
    included_file_warning: ignore

linter:
  rules:
    
    
    prefer_double_quotes: false

    
    
    
    
    always_specify_types: false

    
    
    
    unnecessary_final: false

    
    
    
    
    public_member_api_docs: false

    
    
    prefer_expression_function_bodies: false