targets:
  $default:
    sources: [
      "packages/todos/lib/core/locator.dart",
      "packages/todos/lib/models.dart"
    ]
    builders:
      json_serializable:
        options:
          explicit_to_json: true
